### ISSUE TITLE
apply_filters_to_feed function is too complex

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/feed-filter#1]
Nice work, @davidag! Exciting to see your plugin land here. 🎉 

I noticed that Flake8's code complexity analysis reports that the `apply_filters_to_feed` function is too complex:

```
feed-filter on master ➤ flake8
./pelican/plugins/feed_filter/feed_filter.py:49:1: C901 'apply_filters_to_feed' is too complex (13)
```

You might consider breaking up that function into multiple, smaller functions. But I can understand if you'd rather not do so merely to make Flake8 happy, so if that's the case, feel free to close this issue. 😊

**Comment by davidag** [comment]
@justinmayer Thank you for the report! :relaxed:
